# Generated by Django 4.1.2 on 2022-10-14 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assessment',
            name='user',
        ),
    ]
