# Generated by Django 4.1.2 on 2022-10-14 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0002_remove_assessment_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Assessment',
        ),
        migrations.DeleteModel(
            name='Bulletin',
        ),
    ]
